name: mnist-benchmarks
version: 0.1.0.0

ghc-options: -Wall -O2

data-files: data/*.gz

default-extensions:
  - BangPatterns
  - LambdaCase
  - OverloadedStrings
  - ViewPatterns
  - BangPatterns
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - ScopedTypeVariables
  - TypeApplications
  - ViewPatterns
  - NoImplicitPrelude
  - ConstraintKinds
  - KindSignatures

dependencies:
  - base
  - bytestring
  - containers
  - hmatrix
  - microlens-platform
  - monad-loops
  - mtl
  - mwc-random
  - safe-exceptions
  - statistics
  - text
  - unordered-containers
  - vector
  - criterion
  - proto-lens
  - random
  - HUnit
  - split
  - zlib
  - binary
  - mnist-idx
  - transformers

  - grenade

  - backprop
  - deepseq
  - bifunctors
  - time
  - type-combinators
  - directory
  - generics-sop

  - tensorflow-core-ops
  - tensorflow-opgen
  - tensorflow-ops
  - tensorflow-proto
  - tensorflow-test
  - tensorflow

library:
  source-dirs: src

executables:
  tf_mnist:
    main: bench/MNIST/Tensorflow.hs
    dependencies:
    - mnist-benchmarks

  bp_mnist:
    main: bench/MNIST/Backprop.hs
    dependencies:
    - mnist-benchmarks


  # tests:
  #   doctest:
  #     main: DocTest.hs
  #     source-dirs: test
  #     dependencies:
  #       - mnist-benchmarks
  #       - doctest
  #
  #   spec:
  #     main: Spec.hs
  #     source-dirs: test
  #     dependencies:
  #       - mnist-benchmarks
  #       - hspec
