name: mnist-benchmarks
version: 0.1.0.0

ghc-options: -optl-fuse-ld=gold -Wall
ld-options:  -fuse-ld=gold

data-files: data/*.gz

default-extensions:
  - BangPatterns
  - LambdaCase
  - OverloadedStrings
  - ViewPatterns
  - BangPatterns
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - ScopedTypeVariables
  - TypeApplications
  - ViewPatterns
  - NoImplicitPrelude

dependencies:
  - base
  - bytestring
  - containers
  - hmatrix
  - microlens-platform
  - monad-loops
  - mtl
  - mwc-random
  - safe-exceptions
  - statistics
  - text
  - unordered-containers
  - vector
  - criterion
  - proto-lens
  - random
  - HUnit
  - split
  - zlib
  - binary
  - mnist-idx
  - transformers

  - backprop

  - grenade

  - tensorflow-core-ops
  - tensorflow-opgen
  - tensorflow-ops
  - tensorflow-proto
  - tensorflow-test
  - tensorflow

library:
  source-dirs: bench

  # tests:
  #   doctest:
  #     main: DocTest.hs
  #     source-dirs: test
  #     dependencies:
  #       - mnist-benchmarks
  #       - doctest
  #
  #   spec:
  #     main: Spec.hs
  #     source-dirs: test
  #     dependencies:
  #       - mnist-benchmarks
  #       - hspec
