flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:HuwCampbell/grenade
    commit: '9509719'
  extra-dep: true
extra-deps:
- concurrent-output-1.7.9
- hedgehog-0.1
- wl-pprint-annotated-0.0.1.4
- tensorflow-0.1.0.2
- tensorflow-core-ops-0.1.0.0
- tensorflow-opgen-0.1.0.0
- tensorflow-ops-0.1.0.0
- tensorflow-proto-0.1.0.0
resolver: nightly-2017-11-06
